export enum RoutesEnum {
  mainScreen = '/',
  paymentTransactions = '/payment-transactions',
  documentFlow = '/document-flow',
  accountsContracts = '/accounts-contracts',
  accommodationFacilities = '/accommodation-facilities',
  paymentMethods = '/payment-methods',
  authorization = '/authorization',
  registration = '/registration',
  emailConfirmation = '/email-confirmation',
  company = '/company',
  editCompany = '/edit-company',
  employee = '/company/employee',
  founder = '/company/founder',
  manager = '/company/manager',
  noMatch = '*',
}
